### ISSUE TITLE
Support for building on Linux

### ISSUE THREAD

**Issue by luxxxxy** [Crabapple-iOS/Crabapple#1]
Title. Rust likes to assume that it's impossible to build for macOS/iOS outside of Linux.

**Comment by luxxxxy** [comment]
Turns out you can, you just gotta have [cctools-port](https://github.com/tpoechtrager/cctools-port).

And add this to `~/.cargo/config`
```toml
[target.aarch64-apple-ios]
linker = "/opt/cctools-port/bin/aarch64-apple-darwin-clang"
ar = "/opt/cctools-port/bin/aarch64-apple-darwin-ar"
```
